### ISSUE TITLE
Footer content should be responsive

### ISSUE THREAD

**Issue by manishadayal** [manishadayal/themegitam#4]
Footer content should be responsive
![2021-01-27 19_40_40-Dashboard](https://user-images.githubusercontent.com/60266068/106003459-3a2a8680-60d8-11eb-8b32-b59238216701.png)
![2021-01-27 19_42_21-GITAM_ Log in to the site](https://user-images.githubusercontent.com/60266068/106003473-3bf44a00-60d8-11eb-9473-d99a52ac00eb.png)

**Comment by Rohitsharma2019** [comment]
Fixed #6
